# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml

- task: SoapUIProForAzureDevOpsTask@1
  inputs:
    testRunnerPath: "C:\\Program Files\\SmartBear\\ReadyAPI-2.7.0\\bin\\testrunner.bat"
    project: "D\\SoapUI\\PoC\\ProjectBlue-readyapi-project.xml"